version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: reservai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/ReservAI.Api
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./backend/ReservAI.Api:/app

volumes:
  postgres_data:
